name: package
on:
  push:
    tags: ["*"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"
      - name: Install Python and PIP
        run: sudo apt-get install pip python3-venv --no-install-recommends -yq
      - name: Create venv
        run: |
              python3 -m venv test_venv
              source test_venv/bin/activate
              python --version
      - name: Install libs
        run: pip install -e .[dev]
      - name: Check pylint
        run: pylint -rn -sn -E ./pyonf/
      - name: Check mypy
        run: mypy --install-types --ignore-missing-imports --check-untyped-defs --non-interactive ./pyonf/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "1"
      - name: Install Python and PIP
        run: sudo apt-get install pip python3-venv --no-install-recommends -yq
      - name: Install build
        run: pip3 install build
      - name: Build package
        run: python3 -m build
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/dist/*.whl